VAGRANTFILE_API_VERSION = '2'.freeze
INFRASTRUCTURE_REPO = '/home/infrastructure'.freeze
HYPERVISOR = /linux/ =~ RUBY_PLATFORM ? :lxc : :virtualbox
DEVENV_ROOT=File.expand_path(__dir__ + '/../../cache/repos/')
ANSIBLE_DIR=File.expand_path(__dir__ + '/../../ansible/')

subenvironment='devenv'
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder '../../', INFRASTRUCTURE_REPO, create: true
  config.vm.synced_folder ENV['HOME'], '/home/me', create: true

  # FIXME use Locb::CLI::DEVENV_IP instead of hardcode 10.0.0.4
  config.ssh.forward_agent = true
  if HYPERVISOR == :virtualbox
    config.vm.define 'develop' do |vm_config|
      vm_config.vm.box = 'boxesio/xenial64-standard'
      vm_config.vm.network :private_network, ip: '10.0.4.3'
      vm_config.vm.provider 'virtualbox' do |v|
        v.memory = 3000
        v.cpus = 2
      end
    end
  else
    config.vm.define 'develop' do |vm_config|
      vm_config.vm.box = 'magec/xenial64-lxc'
      vm_config.vm.provider :lxc do |lxc|
        lxc.container_name = 'locb-development'
        lxc.customize 'network.ipv4', '10.0.3.5/24'
        lxc.customize 'network.ipv4.gateway', '10.0.3.1'
      end
    end
  end

  # Fetch repos
  config.vm.provision(
    'fetch_repos',
    type: 'shell',
    path: File.join(__dir__, '/../scripts/repos.sh'),
    privileged: false
  )

  config.vm.provision 'bootstrap', type: 'ansible' do |ansible|
    ansible.playbook = "#{ANSIBLE_DIR}/puppet.yml"
    ansible.config_file = "#{ANSIBLE_DIR}/ansible.cfg"
    ansible.compatibility_mode = '2.0'
    ansible.extra_vars = {
      set_hostname: 'develop',
      set_domain: 'dev.locb.xyz',
      set_environment: 'development',
      set_subenvironment: 'devenv',
      infrastructure_path: INFRASTRUCTURE_REPO,
      apply_puppet: false
    }
  end
  config.vm.provision 'puppet', type: 'shell', inline: "cd #{INFRASTRUCTURE_REPO}/puppet; FACTER_SUBENVIRONMENT=#{subenvironment} puppet apply environments/devenv/manifests/servers.pp --confdir . --environment=development --show_diff"
end
